export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	USER_UPDATE: 'USER_UPDATE',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	SET_MEAL_DATA: 'SET_MEAL_DATA',
	SET_MEALS_DATA: 'SET_MEALS_DATA',
	RESET_MEAL_DATA: 'RESET_MEAL_DATA',
	// START_EDITING_MEAL: 'START_EDITING_MEAL',
	// CANCEL_EDITING_MEAL: 'CANCEL_EDITING_MEAL',
	// UPDATE_EDITED_MEAL_DATA: 'UPDATE_EDITED_MEAL_DATA',
};
